export const PLANS = [
  {
    id: "free",
    name: "Free",
    price: 0,
    period: "forever",
    description: "Get started with the basics",
    features: [
      "10 Aura AI messages / day",
      "5 doubts / month",
      "View community feed",
      "1 Study Room / day",
      "Basic mock tests",
      "Leaderboard access",
    ],
    notIncluded: ["Unlimited AI chat", "Mentor sessions", "Advanced analytics", "Hiring board", "Certificates"],
  },
  {
    id: "pro",
    name: "Pro",
    price: 299,
    period: "month",
    description: "For serious learners",
    features: [
      "Unlimited Aura AI messages",
      "Unlimited doubts",
      "All Study Rooms",
      "1 Mentor session / month",
      "All mock tests + analytics",
      "Priority support",
      "Leaderboard access",
      "Community feed — full access",
    ],
    notIncluded: ["5 Mentor sessions / month", "Project reviews", "Hiring board", "Certificates"],
    highlight: true,
    badge: "Most Popular",
    razorpayPlanId: "plan_pro_monthly",
  },
  {
    id: "elite",
    name: "Elite",
    price: 699,
    period: "month",
    description: "For future industry leaders",
    features: [
      "Everything in Pro",
      "5 Mentor sessions / month",
      "Project reviews by mentors",
      "Hiring board access",
      "Certificate of completion",
      "Direct mentor DMs",
      "Early access to new features",
      "Dedicated support channel",
    ],
    notIncluded: [],
    badge: "Best Value",
    razorpayPlanId: "plan_elite_monthly",
  },
];
