export const TOPICS = [
  { id: "1", name: "Arduino", slug: "arduino", category: "robotics", icon: "🤖", color: "#00979D" },
  { id: "2", name: "Raspberry Pi", slug: "raspberry-pi", category: "robotics", icon: "🍓", color: "#C51A4A" },
  { id: "3", name: "ROS (Robot Operating System)", slug: "ros", category: "robotics", icon: "⚙️", color: "#22314E" },
  { id: "4", name: "Servo Motors", slug: "servo-motors", category: "robotics", icon: "🔧", color: "#7C3AED" },
  { id: "5", name: "3D Printing", slug: "3d-printing", category: "robotics", icon: "🖨️", color: "#F59E0B" },
  { id: "6", name: "Drone Programming", slug: "drone", category: "robotics", icon: "🚁", color: "#2563EB" },
  { id: "7", name: "SLAM Navigation", slug: "slam", category: "robotics", icon: "🗺️", color: "#059669" },
  { id: "8", name: "ESP32/ESP8266", slug: "esp32", category: "iot", icon: "📡", color: "#E74C3C" },
  { id: "9", name: "MQTT Protocol", slug: "mqtt", category: "iot", icon: "📨", color: "#8E44AD" },
  { id: "10", name: "AWS IoT Core", slug: "aws-iot", category: "iot", icon: "☁️", color: "#FF9900" },
  { id: "11", name: "Home Automation", slug: "home-automation", category: "iot", icon: "🏠", color: "#1ABC9C" },
  { id: "12", name: "Sensor Networks", slug: "sensors", category: "iot", icon: "🌡️", color: "#3498DB" },
  { id: "13", name: "Edge Computing", slug: "edge-computing", category: "iot", icon: "💻", color: "#2ECC71" },
  { id: "14", name: "LoRaWAN", slug: "lorawan", category: "iot", icon: "📶", color: "#E67E22" },
  { id: "15", name: "Machine Learning", slug: "machine-learning", category: "ai", icon: "🧠", color: "#9B59B6" },
  { id: "16", name: "Deep Learning", slug: "deep-learning", category: "ai", icon: "🔮", color: "#2980B9" },
  { id: "17", name: "Computer Vision", slug: "computer-vision", category: "ai", icon: "👁️", color: "#27AE60" },
  { id: "18", name: "Natural Language Processing", slug: "nlp", category: "ai", icon: "💬", color: "#C0392B" },
  { id: "19", name: "Reinforcement Learning", slug: "reinforcement-learning", category: "ai", icon: "🎮", color: "#16A085" },
  { id: "20", name: "TensorFlow / PyTorch", slug: "tensorflow-pytorch", category: "ai", icon: "🔥", color: "#FF6F00" },
  { id: "21", name: "LLMs & Prompt Engineering", slug: "llm", category: "ai", icon: "✨", color: "#7C3AED" },
];
